name: CI pipeline for ssio project
#testing 


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ssio-gateway-env
    steps:
      - uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ssio-project-gateway:latest .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ssio-project-gateway:latest
